### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by printf-ana** [shoumikdey/brute-force#37]
Hey, i'm trying to contributing with some repos for the first time in Github, and i think a good thing to do it's give to user the chance to import any image for the internet, put this link, not just his downloads...
I think an explication can be good in the start of the site too. 
I liked to make some apperances changes, can i?
I'm not sure if i really have to ask permission, but i will wait for that.

**Comment by shoumikdey** [comment]
Hi @printf-ana , do you suggest a feature in which I can put an URL of an image for prediction ? If that is so, you can surely go ahead. Yes, all changes that you would like to make are welcomed. You don't need to ask for permission as such, send a Pull Request with the changes to this repo and we will verify it. Since you are new to github, I would suggest that you go through a few youtube videos about contributing in github. Best!
